stake2earn Pledge
Agoric/validator-profiles pull request #18
Opened 2022-02-17 14:06 UTC by AlexDCryptoC

2022-02-19 17:15 UTC, jeetraut requested changes
Add explorer link

2022-02-19 17:15 UTC, jeetraut commented on README.md
> +I, stake2earn hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may los
```suggestion
[stake2earn Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1dm5l7udmdc66lza5dvhtmqw0m6u640qc0c2ymg)
I, stake2earn hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may lose delegation staked to me.: 
```

2022-02-21 10:41 UTC, AlexDCryptoC reviewed
Sure

2022-03-04 17:50 UTC, jeetraut commented
Hi. Thanks for the contribution, but we need your README.md file to be in a subfolder. Take a look at https://github.com/Agoric/validator-profiles/pull/2 for an example where the README.md file is BlockShark/README.md.

We could try to resolve the conflicts in this branch / PR, but that would be kind of a hassle, so... can we ask you to just make another PR?

2022-03-04 17:50 UTC, closed without merging