Stakely Pledge
Agoric/validator-profiles pull request #25
Opened 2022-02-17 16:41 UTC by iicc1

2022-02-19 17:26 UTC, jeetraut requested changes
Add explorer link

2022-02-19 17:26 UTC, jeetraut commented on Stakely/README.md
> +
```suggestion
[Stakely Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1mxhgvj2c93xahahx9d9fc7rwwtufqza5cn6uhn)
```

2022-02-28 16:51 UTC, merged

2022-03-31 19:28 UTC, iicc1 commented
We created a page with information about Agoric and a staking tutorial in both English and Spanish. It contains a brief introduction to Agoric, with links and a simple staking calculator tool that will work when the staking rewards start. It also contains a step-by-step staking tutorial and frequently asked questions regarding Agoric staking.

- English: https://stakely.io/en/agoric-staking
- Spanish: https://stakely.io/es/agoric-staking

More coming soon!

2022-07-25 10:35 UTC, iicc1 commented
We added Agoric to our load balancer for web3 APIs. This free service aggregates several public and private nodes and the requests are routed among them. It has many features like health checks, retires on errors, CORS-enabled requests, caching, etc. It can be used for production-ready apps. We also deployed our own Agoric RPC and LCD and connected them to the tool

https://agoric-rpc.stakely.io --> Aggregates 10 Agoric public nodes
https://agoric-lcd.stakely.io --> Aggregates 6 Agoric public nodes