TheNOP.io Pledge
Agoric/validator-profiles pull request #30
Opened 2022-02-17 17:13 UTC by EmreNOP

2022-02-19 17:44 UTC, jeetraut requested changes
Add explorer link

2022-02-19 17:44 UTC, jeetraut commented on README.md
> +I,TheNOP.io hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may lose
```suggestion
[TheNop.io Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper17k4wstnvtyt7pt8qnfamrdpkkj7f5qqvf6heg3)
I,TheNOP.io hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may lose delegation staked to me.:
```

2022-04-04 10:47 UTC, EmreNOP reviewed
ok

2022-04-04 10:53 UTC, EmreNOP commented
Video about, Keplr installation, coinlist process and delegation for Turkish community

https://www.youtube.com/watch?v=rO0hzWXOZ8I

2022-10-24 16:15 UTC, jeetraut approved these changes

2022-10-24 16:15 UTC, merged