StakeAngle Pledge
Agoric/validator-profiles pull request #32
Opened 2022-02-17 17:29 UTC by Cryptoperchik

2022-02-17 19:28 UTC, dckc reviewed
This looks pretty good, to me. I'll leave approval to @jeetraut 

@jeetraut it looks like the markdown we generated had some incomplete links.

2022-02-17 19:28 UTC, dckc commented on StakeAngle/README.md
> +1. The hardware my node will run meets the requirements detailed in the [Agoric Validator Runbooks](https://github.com/Agoric/agoric-sdk/wiki/Runbook%...)
```suggestion
1. The hardware my node will run meets the requirements detailed in the [Agoric Validator Runbooks](https://github.com/Agoric/agoric-sdk/wiki/Runbooks)
```

2022-02-17 19:28 UTC, dckc commented on StakeAngle/README.md
> +6. I will report bugs I discover through the process described in the [Agoric Reporting a Security Bug Runbook](https://github.com/Agoric/agoric-sdk/wiki/Runbook%...)
```suggestion
6. I will report bugs I discover through the process described in the [Agoric Reporting a Security Bug Runbook](https://github.com/Agoric/agoric-sdk/wiki/Runbook%3A-Reporting-a-Security-Bug)
```

2022-02-17 19:28 UTC, dckc commented on StakeAngle/README.md
> +7. I will follow the guidelines described in the [Agoric Security Coordination - Emergency Bug Response with Chain Validators Runbook](https://github.com/Agoric/agoric-sdk/wiki/Runbook%...) to mainta
```suggestion
7. I will follow the guidelines described in the [Agoric Security Coordination - Emergency Bug Response with Chain Validators Runbook](https://github.com/Agoric/agoric-sdk/wiki/Runbook%3A-Security-Coordination---Emergency-Bug-Response-with-Chain-Validators) to maintain the health of the chain
```

2022-02-18 06:44 UTC, dckc approved these changes

2022-02-19 17:53 UTC, jeetraut requested changes
Add explorer link

2022-02-19 17:53 UTC, jeetraut commented on StakeAngle/README.md
> +
```suggestion
[StakeAngle Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper13pkmjguqfjyct7jf32fezqd53590l7mtg2cnwc)
```

2022-02-28 21:06 UTC, merged