1ce Pledge
Agoric/validator-profiles pull request #34
Opened 2022-02-17 18:58 UTC by humantraffic

2022-02-17 19:21 UTC, dckc commented
Hi. Thanks for your contribution!

But your README.md should be in a folder named after your validator. Please don't change the top level README.md.

2022-02-17 19:22 UTC, dckc requested changes
please move your README.md to its own folder

2022-02-17 19:37 UTC, dckc commented
11a502a is better, but it deletes the top level README.md

2022-02-19 17:55 UTC, jeetraut requested changes
Add explorer link

2022-02-22 19:50 UTC, humantraffic commented on 1ce/README.md
> +
add

2022-03-01 04:51 UTC, merged

2022-03-01 05:03 UTC, dckc commented
Looks like this PR deleted the top-level readme