Update README.md
Agoric/validator-profiles pull request #4
Opened 2022-02-17 08:53 UTC by polyackiy

Agoric Pledge Markdown
moniker: AlphaBravo
email: polyackiy@gmail.com

2022-02-18 19:11 UTC, jeetraut requested changes
Add Explorer Link

2022-02-18 19:11 UTC, jeetraut commented on README.md
```suggestion
[AlphaBravo Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1cvr94kqlp9ss4mx5gkm76h8jf5lnhwvvrav9nd)
```

2022-03-03 20:55 UTC, dckc commented
Hi. Thanks for the contribution, but we need your README.md file to be in a subfolder. Take a look at #2 for an example where the README.md file is `BlockShark/README.md`.

We could try to resolve the conflicts in this branch / PR, but that would be kind of a hassle, so... can we ask you to just make another PR?

2022-03-03 20:55 UTC, closed without merging

2022-03-03 22:59 UTC, polyackiy commented
> Hi. Thanks for the contribution, but we need your README.md file to be in a subfolder. Take a look at #2 for an example where the README.md file is `BlockShark/README.md`.
> 
> We could try to resolve the conflicts in this branch / PR, but that would be kind of a hassle, so... can we ask you to just make another PR?

Sorry for taking so long. Another [PR](https://github.com/Agoric/validator-profiles/pull/88)