Update Agaram.ai README.md
Agoric/validator-profiles pull request #42
Opened 2022-02-18 00:26 UTC by Agarams

Agaram.ai ReadMe update for pledge

2022-03-01 04:48 UTC, jeetraut requested changes
Add explorer link

2022-03-01 04:48 UTC, jeetraut commented on Agaramai/README.md
> +
```suggestion
[Agaram.ai Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1jjx0vc6dxe44mxzyq2la22j86avdmj0qpkum7f)
```

2022-03-03 03:17 UTC, Agarams commented on Agaramai/README.md
> +
Sure

2022-03-04 17:51 UTC, jeetraut commented
Hi. Thanks for the contribution, but we need your README.md file to be in a subfolder. Take a look at https://github.com/Agoric/validator-profiles/pull/2 for an example where the README.md file is BlockShark/README.md.

We could try to resolve the conflicts in this branch / PR, but that would be kind of a hassle, so... can we ask you to just make another PR?

2022-03-04 17:51 UTC, closed without merging