blackpaopao pledge
Agoric/validator-profiles pull request #47
Opened 2022-02-18 05:57 UTC by woshiwjw11

2022-02-19 18:45 UTC, jeetraut requested changes
Add explorer link

2022-02-19 18:45 UTC, jeetraut commented on README.md
> +I,jiawei wang hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may los
```suggestion
[blackpaopao Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1myk93jzj5n5adfp2d4pu28gjxcmn9v4ezlv795)
I,jiawei wang hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may lose delegation staked to me.:
```

2022-02-21 03:42 UTC, woshiwjw11 commented
thank you

2022-03-04 17:54 UTC, jeetraut commented
Hi. Thanks for the contribution, but we need your README.md file to be in a subfolder. Take a look at https://github.com/Agoric/validator-profiles/pull/2 for an example where the README.md file is BlockShark/README.md.

We could try to resolve the conflicts in this branch / PR, but that would be kind of a hassle, so... can we ask you to just make another PR?

2022-03-04 17:54 UTC, closed without merging