Pledge for hiretrade
Agoric/validator-profiles pull request #48
Opened 2022-02-18 07:47 UTC by shivlim

2022-02-18 21:24 UTC, dckc requested changes
Hi.  Thanks for your pledge! But we need you to move it down under a folder rather than changing the top level README.md

2022-02-18 21:45 UTC, shivlim commented
> Hi. Thanks for your pledge! But we need you to move it down under a folder rather than changing the top level README.md

Updated now. Thanks

2022-02-19 18:48 UTC, jeetraut requested changes
Add explorer Link

2022-02-19 18:48 UTC, jeetraut commented on hiretrade/README.md
> +I, hiretrade hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may lose
```suggestion
[hiretrade Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1s55crdh7fgn8z7vvhdfc52f8zwq03cng9wryuj)
I, hiretrade hereby commit to the following work and support for the benefit of the Agoric Network and Community. If, for any reason, I do not meet these commitments then I understand that I may lose delegation staked to me.:
```

2022-02-19 19:03 UTC, shivlim commented
> Add explorer Link

Done. Thanks

2022-03-04 17:54 UTC, jeetraut commented
Hi. Thanks for the contribution, but we need your README.md file to be in a subfolder. Take a look at https://github.com/Agoric/validator-profiles/pull/2 for an example where the README.md file is BlockShark/README.md.

We could try to resolve the conflicts in this branch / PR, but that would be kind of a hassle, so... can we ask you to just make another PR?

2022-03-04 17:54 UTC, closed without merging