QuantNode Pledge
Agoric/validator-profiles pull request #52
Opened 2022-02-18 12:44 UTC by sshamanov

2022-02-19 20:49 UTC, jeetraut requested changes
Add explorer link

2022-02-19 20:49 UTC, jeetraut commented on QuantNode/README.md
> +
```suggestion
[Quantnode Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper197cjvysnn34czsptw46vfp5swr525xhu4k5h0l)
```

2022-02-20 10:32 UTC, sshamanov reviewed
explorere link added

2022-02-20 10:36 UTC, sshamanov reviewed
added explorer link

2022-03-01 04:45 UTC, jeetraut approved these changes
Looks good

2022-03-01 04:50 UTC, merged