Agoric Validator Pledge - Wanderer Staking
Agoric/validator-profiles pull request #6
Opened 2022-02-17 09:14 UTC by Wanderer-Cry

2022-02-18 19:42 UTC, jeetraut requested changes
Add explorer link

2022-02-18 19:42 UTC, jeetraut commented on Wanderer Staking/README.md
> +
```suggestion
[Wanderer Staking Explorer Link](https://main.explorer.agoric.net/validator/agoricvaloper1kxekyxvywtqexan9m9uju69ger67vefeeuhgrz)
```

2022-02-19 09:56 UTC, Wanderer-Cry commented on Wanderer Staking/README.md
> +
Agreed.

2022-02-19 09:58 UTC, Wanderer-Cry commented
Added. Thank you

2022-02-22 16:34 UTC, Wanderer-Cry reviewed
Agreed

2022-02-22 16:35 UTC, Wanderer-Cry commented
> Add explorer link

Added, thanks

2022-02-28 15:58 UTC, merged