add KingSuper pledge
Agoric/validator-profiles pull request #73
Opened 2022-02-19 07:26 UTC by aditya-manit

2022-02-20 00:21 UTC, jeetraut requested changes
Add explorer link

2022-02-20 00:21 UTC, jeetraut commented on KingSuper/README.md
> +
```suggestion
[KingSuper](https://main.explorer.agoric.net/validator/agoricvaloper1fy8r6zq3dde6n7ak6eqy5zsrp3s7sz833dmv32)
```

2022-02-28 15:33 UTC, jeetraut reviewed
Looks good!

2022-02-28 15:33 UTC, merged

2022-03-25 19:19 UTC, dckc commented
@aditya-manit is doing a great job helping to review 1 BLD requests (#80).

2022-03-28 14:50 UTC, aditya-manit commented
Thanks @dckc :D :D